--/* ==============================================================
--   CREACIÓN TABLA MODELO_LM_202507_TRAIN
--   Selecciona campos de entrenamiento desde MODELO_LM_202507_OPTIMIZADO
--   ============================================================== */

CREATE OR REPLACE TABLE OPX.P_DDV_OPX_MDPREDICTIVO.MODELO_LM_202507_TRAIN AS

-- Primero verificar cantidad de registros esperados
-- SELECT COUNT(DISTINCT LCC_COMCOR) FROM OPX.P_DDV_OPX_MDPREDICTIVO.MODELO_LM_202507_OPTIMIZADO 
-- WHERE (I_RESOLUCION IS NULL OR I_RESOLUCION NOT IN (408, 409, 410, 411, 401, 402, 406, 305, 306))
-- AND FECHA_EMISION_DT < CURRENT_DATE();

-- Seleccionar solo registros únicos y transformar columnas
SELECT 
    /* ===== IDENTIFICADORES ===== */
    m.AFILIADO_RUT,
    m.LCC_COMCOR,
    m.LCC_COMCOD,
    
    /* ===== NUEVAS COLUMNAS DE FECHA (limpieza valores 1900) ===== */
    CASE 
        WHEN m.FECHA_EMP_RECEPCION IS NULL THEN NULL
        WHEN m.FECHA_EMP_RECEPCION = '1900-01-01' THEN NULL
        ELSE m.FECHA_EMP_RECEPCION
    END AS FECHA_EMP_RECEPCION,
    CASE 
        WHEN m.FECHA_EMP_ENVIO IS NULL THEN NULL
        WHEN m.FECHA_EMP_ENVIO = '1900-01-01' THEN NULL
        ELSE m.FECHA_EMP_ENVIO
    END AS FECHA_EMP_ENVIO,
    CASE 
        WHEN m.FECHA_NAC_HIJO IS NULL THEN NULL
        WHEN m.FECHA_NAC_HIJO = '1900-01-01' THEN NULL
        ELSE m.FECHA_NAC_HIJO
    END AS FECHA_NAC_HIJO,
    
    /* ===== CÁLCULOS DE DIFERENCIAS DE FECHAS ===== */
    CASE 
        WHEN m.FECHA_EMP_RECEPCION IS NULL THEN NULL
        WHEN m.FECHA_EMP_RECEPCION = '1900-01-01' THEN NULL
        WHEN datediff(m.FECHA_EMP_RECEPCION, m.FECHA_RECEPCION) > 30 THEN 30
        WHEN datediff(m.FECHA_EMP_RECEPCION, m.FECHA_RECEPCION) < -30 THEN -30
        ELSE datediff(m.FECHA_EMP_RECEPCION, m.FECHA_RECEPCION)
    END AS DIAS_RECEPCION_A_EMPLEADOR,
    
    CASE 
        WHEN m.FECHA_EMP_ENVIO IS NULL THEN NULL
        WHEN m.FECHA_EMP_ENVIO = '1900-01-01' THEN NULL
        WHEN datediff(m.FECHA_EMP_ENVIO, m.FECHA_RECEPCION) > 30 THEN 30
        WHEN datediff(m.FECHA_EMP_ENVIO, m.FECHA_RECEPCION) < -30 THEN -30
        ELSE datediff(m.FECHA_EMP_ENVIO, m.FECHA_RECEPCION)
    END AS DIAS_RECEPCION_A_ENVIO,
    
    CASE 
        WHEN datediff(m.FECHA_RECEPCION, m.FECHA_INICIO) > 30 THEN 30
        WHEN datediff(m.FECHA_RECEPCION, m.FECHA_INICIO) < -30 THEN -30
        ELSE datediff(m.FECHA_RECEPCION, m.FECHA_INICIO)
    END AS DIAS_INICIO_A_RECEPCION,
    
    CASE 
        WHEN datediff(m.FECHA_EMISION_DT, m.FECHA_INICIO) > 30 THEN 30
        WHEN datediff(m.FECHA_EMISION_DT, m.FECHA_INICIO) < -30 THEN -30
        ELSE datediff(m.FECHA_EMISION_DT, m.FECHA_INICIO)
    END AS DIAS_INICIO_A_EMISION,
    
    CASE 
        WHEN datediff(m.FECHA_RECEPCION, m.FECHA_EMISION_DT) > 30 THEN 30
        WHEN datediff(m.FECHA_RECEPCION, m.FECHA_EMISION_DT) < -30 THEN -30
        ELSE datediff(m.FECHA_RECEPCION, m.FECHA_EMISION_DT)
    END AS DIAS_EMISION_A_RECEPCION,
    
    -- Flag de envío tardío del empleador
    CASE 
        WHEN m.FECHA_EMP_RECEPCION IS NULL OR m.FECHA_EMP_ENVIO IS NULL THEN NULL
        WHEN m.FECHA_EMP_RECEPCION = '1900-01-01' OR m.FECHA_EMP_ENVIO = '1900-01-01' THEN NULL
        WHEN datediff(m.FECHA_EMP_ENVIO, m.FECHA_EMP_RECEPCION) > 3 
        THEN 1 
        ELSE 0 
    END AS ENVIO_TARDIO_EMPLEADOR,
    
    /* ===== FECHAS Y DATOS BÁSICOS ===== */
    m.FECHA_EMISION_DT,
    m.FECHA_RECEPCION,
    m.FECHA_INICIO,
    m.FECHA_TERMINO,
    m.DIASSOLICITADO,
    m.COT_EDAD,
    -- Estandarizar COT_GENERO a Fem/Masc
    CASE 
        WHEN UPPER(TRIM(m.COT_GENERO)) IN ('FEM', 'F', 'FEMENINO') THEN 'Fem'
        WHEN UPPER(TRIM(m.COT_GENERO)) IN ('MASC', 'M', 'MASCULINO') THEN 'Masc'
        WHEN m.COT_GENERO IN ('Fem', 'Masc') THEN m.COT_GENERO  -- Ya está estandarizado
        ELSE NULL
    END AS COT_GENERO,
    m.DEUDA_SIN_I,
    m.DEUDA_SIN_I_ULT12M,
    
    /* ===== DIAGNÓSTICO ===== */
    m.CIE_F,
    m.CIE_F_COD,
    m.CIE_GRUPO,
    m.LM_DIAGNOSTICO,
    m.LM_ANTECEDENTES_CLINICOS,
    m.LM_FORMATO,
    m.LM_REPOSO_TIPO,
    
    -- TIPO_F_LM y TIPO_F_LM_COD con fallback a LME cuando están en blanco
    COALESCE(
        NULLIF(m.TIPO_F_LM, ''),
        CASE m.`lic_codigo_tipo_licencia`
            WHEN 1 THEN 'ENFERMEDAD COMUN'
            WHEN 2 THEN 'PRORROGA MEDICINA PREVENTIVA'
            WHEN 3 THEN 'MATERNAL'
            WHEN 4 THEN 'ENFERM. HIJO < 1 AÑO'
            WHEN 5 THEN 'ACCIDENTE DEL TRABAJO'
            WHEN 6 THEN 'ENFERMEDAD PROFESIONAL'
            WHEN 7 THEN 'PATOLOGIA DEL EMBARAZO'
            ELSE 'OTRO'
        END
    ) AS TIPO_F_LM,
    COALESCE(NULLIF(m.TIPO_F_LM_COD, 0), m.`lic_codigo_tipo_licencia`, 0) AS TIPO_F_LM_COD,
    
    /* ===== PRESTADOR ===== */
    m.`lic_codigo_tipo_licencia` AS I_TIPOLIC,
    m.N_LICENCIA,
    m.PRESTADOR_RUT,
    -- MEDICO_EXTRANJERO: Se determina si el RUT está en el rango 48-49 millones
    -- TODO[Databricks]: TRY_CAST de Snowflake fue reemplazado por CAST; validar calidad de datos de PRESTADOR_RUT para evitar errores de casteo.
    CASE 
        WHEN CAST(SPLIT_PART(m.PRESTADOR_RUT, '-', 1) AS INTEGER) BETWEEN 48000000 AND 49999999 THEN 1
        ELSE 0
    END AS MEDICO_EXTRANJERO,
    m.PRESTADOR_LOCAL_RUT,
    m.PRESTADOR_ESPECIALIDAD_PSC,
    m.PRESTADOR_TIPO,
    CASE
        WHEN UPPER(m.PRESTADOR_TIPO) = 'MEDICO' THEN 1
        ELSE 0
    END AS IS_MEDICO,
    m.MED_ESPECIALIDAD_LME,
    m.MED_CLASIFICACION,
    m.PREST_TOP_CIE_F,
    m.PREST_TOP_GRUPOCIE,
    ((year(m.FECHA_RECEPCION) - year(m.FECHA_SUSCR_CONTRATO)) * 12 + (month(m.FECHA_RECEPCION) - month(m.FECHA_SUSCR_CONTRATO))) AS MESES_DESDE_CONTRATO,
    ((year(m.FECHA_RECEPCION) - year(m.FECHA_INGRESO_PREST)) * 12 + (month(m.FECHA_RECEPCION) - month(m.FECHA_INGRESO_PREST))) AS MESES_ANTIGUEDAD_PRESTADOR,
    m.COMUNA_REPOSO,
    m.COMUNA_EMISION,
    m.EMPLEADOR_RUT,
    m.EMPLEADOR_MULTIEMPLEADO,
    m.EMPLEADOR_RUT_DISTINTOS_LM_u36m as EMPLEADOS_CON_LM,
    m.RENTA_ESTIMADA,
    m.CALIDAD_TRABAJADOR,
    m.CONTINUA_CALC,
    -- Corregir EPISODIO_FEC_INI cuando es NULL
    CASE 
        WHEN m.EPISODIO_FEC_INI IS NULL THEN TO_DATE(m.FECHA_INICIO)
        ELSE m.EPISODIO_FEC_INI
    END AS EPISODIO_FEC_INI,
    
    CASE
        WHEN m.CONTINUA_CALC = 'S' THEN
            datediff(
                     TO_DATE(m.FECHA_TERMINO),
                     CASE 
                         WHEN m.EPISODIO_FEC_INI IS NULL THEN TO_DATE(m.FECHA_INICIO)
                         ELSE TO_DATE(m.EPISODIO_FEC_INI)
                     END
            ) + 1
        ELSE
            datediff(
                     TO_DATE(m.FECHA_TERMINO),
                     TO_DATE(m.FECHA_INICIO)
            ) + 1
    END AS EPISODIO_ACUM_DIAS,
    
    /* ===== FADE / ALERTAS – ventanas temporales ===== */
    COALESCE(m.FADE_AFILIADO_90D, 0)        AS FADE_AFILIADO_90D,
    COALESCE(m.FADE_AFILIADO_365D, 0)       AS FADE_AFILIADO_365D,
    COALESCE(m.FADE_EMPRESA_90D, 0)         AS FADE_EMPRESA_90D,
    COALESCE(m.FADE_EMPRESA_365D, 0)        AS FADE_EMPRESA_365D,
    COALESCE(m.FADE_PRESTADOR_90D, 0)       AS FADE_PRESTADOR_90D,
    COALESCE(m.FADE_PRESTADOR_365D, 0)      AS FADE_PRESTADOR_365D,
    COALESCE(m.FADE_LICENCIA_7D, 0)         AS FADE_LICENCIA_7D,   -- ±7 días
    
    COALESCE(m.ALERTA_AMARILLA_90D, 0)      AS ALERTA_AMARILLA_90D,
    COALESCE(m.ALERTA_AMARILLA_365D, 0)     AS ALERTA_AMARILLA_365D,
    COALESCE(m.ALERTA_ROJA_90D, 0)          AS ALERTA_ROJA_90D,
    COALESCE(m.ALERTA_ROJA_365D, 0)         AS ALERTA_ROJA_365D,
    
    /* ===== TODAS LAS MÉTRICAS HISTÓRICAS DE MODELO_LM ===== */
    m.COMPIN_CNT,
    m.RN_AFILIADO_HIST AS RN,
    m.CANT_LIC_U1M_CALC,
    m.CANT_LIC_U6M_CALC,
    m.CANT_LIC_U12M_CALC,
    m.CANT_LIC_U24M_CALC,
    m.CANT_LIC_U36M_CALC,
    m.COMPIN_RATIFICA_01,
    m.COMPIN_RATIFICA_06,
    m.COMPIN_RATIFICA_12,
    m.COMPIN_RATIFICA_24,
    m.M_DIASAUTORIZADOS_TOTAL_U1M,
    m.M_DIASAUTORIZADOS_PROMEDIO_U1M,
    m.M_DIASAUTORIZADOS_MAXIMO_U1M,
    m.M_DIASAUTORIZADOS_TOTAL_U6M,
    m.M_DIASAUTORIZADOS_PROMEDIO_U12M,
    m.M_DIASAUTORIZADOS_MAXIMO_U12M,
    m.M_DIASAUTORIZADOS_TOTAL_U12M,
    m.M_DIASAUTORIZADOS_PROMEDIO_U24M,
    m.M_DIASAUTORIZADOS_MAXIMO_U24M,
    m.F_DIAS_PROMEDIO_U1M,
    m.F_DIAS_MINIMO_U6M,
    m.F_DIAS_MINIMO_U12M,
    m.F_DIAS_MINIMO_U24M,
    m.F_DIAS_PROMEDIO_U6M,
    m.F_DIAS_PROMEDIO_U12M,
    m.F_DIAS_PROMEDIO_U24M,
    m.F_DIAS_PROMEDIO_U36M,
    m.F_DIAS_MAXIMO_U6M,
    m.DIFF_DIAS_PERDIDOS_RESOL_MINIMO_U6M,
    m.DIFF_DIAS_PERDIDOS_RESOL_PROMEDIO_U6M,
    m.DIFF_DIAS_PERDIDOS_RESOL_MAXIMO_U6M,
    m.DIFF_DIAS_PERDIDOS_RESOL_PROMEDIO_U12M,
    m.DIFF_DIAS_PERDIDOS_RESOL_PROMEDIO_U24M,
    m.DIFF_DIAS_PERDIDOS_RESOL_PROMEDIO_U36M,
    m.CIE_GRUPO_PSIQUIATRICAS_01,
    m.CIE_GRUPO_PSIQUIATRICAS_06,
    m.CIE_GRUPO_PSIQUIATRICAS_12,
    m.CIE_GRUPO_PSIQUIATRICAS_24,
    m.CIE_GRUPO_PSIQUIATRICAS_36,
    m.DIASSOLICITADO_TOTAL_U1M,
    m.DIASSOLICITADO_PROMEDIO_U1M,
    m.DIASSOLICITADO_MAXIMO_U1M,
    m.DIASSOLICITADO_TOTAL_U6M,
    m.DIASSOLICITADO_PROMEDIO_U6M,
    m.DIASSOLICITADO_MAXIMO_U6M,
    m.DIASSOLICITADO_TOTAL_U12M,
    m.DIASSOLICITADO_PROMEDIO_U12M,
    m.DIASSOLICITADO_MAXIMO_U12M,
    m.DIASSOLICITADO_TOTAL_U24M,
    m.DIASSOLICITADO_PROMEDIO_U24M,
    m.DIASSOLICITADO_TOTAL_U36M,
    m.TIEMPO_PROMEDIO_RESOLUCION_COMPIN_01,
    m.TIEMPO_PROMEDIO_RESOLUCION_COMPIN_06,
    m.TIEMPO_PROMEDIO_RESOLUCION_COMPIN_12,
    m.TIEMPO_PROMEDIO_RESOLUCION_COMPIN_24,
    m.TIEMPO_PROMEDIO_RESOLUCION_COMPIN_36,
    m.PORCENTAJE_LM_MODIFICADA_01,
    m.PORCENTAJE_LM_MODIFICADA_06,
    m.PORCENTAJE_LM_MODIFICADA_12,
    m.PORCENTAJE_LM_MODIFICADA_24,
    m.PORCENTAJE_LM_MODIFICADA_36,
    m.LM_MODIFICADA_01,
    m.LM_MODIFICADA_06,
    m.LM_MODIFICADA_12,
    m.LM_MODIFICADA_24,
    m.LM_MODIFICADA_36,
    m.LM_DENEGADAS_COMPIN_01,
    m.LM_DENEGADAS_COMPIN_06,
    m.LM_DENEGADAS_COMPIN_12,
    m.LM_DENEGADAS_COMPIN_36,
    m.LM_TIPO_ENF_COMUN_12,
    m.LM_TIPO_ENF_COMUN_24,
    m.LM_TIPO_ENF_COMUN_36,
    m.LM_CON_PERITAJE_12,
    m.CTD_ENVIA_PERITAJE_PROMEDIO_U12M,
    m.CTD_ENVIA_INFORME_MEDICO_PROMEDIO_U12M,
    m.CTD_ENVIA_PERITAJE_U12M,
    m.SIN_SUBSIDIO_01,
    m.SIN_SUBSIDIO_12,
    m.SIN_SUBSIDIO_24,
    m.MEDICO_LM_RECHAZADAS_ISAPRE_U1M,
    m.MEDICO_LM_RECHAZADAS_ISAPRE_U6M,
    m.MEDICO_LM_RECHAZADAS_ISAPRE_U12M,
    m.MEDICO_LM_RECHAZADAS_ISAPRE_U24M,
    m.MEDICO_LM_RECHAZADAS_ISAPRE_U36M,
    m.MEDICO_LM_RECIBIDAS_TOTAL_U1M,
    m.MEDICO_LM_RECIBIDAS_TOTAL_U6M,
    m.MEDICO_LM_RECIBIDAS_TOTAL_U12M,
    m.MEDICO_LM_RECIBIDAS_TOTAL_U24M,
    m.MEDICO_LM_RECIBIDAS_TOTAL_U36M,
    m.MEDICO_DIAS_MODIFICADOS_SUM_ISAPRE_U1M,
    m.MEDICO_DIAS_MODIFICADOS_SUM_ISAPRE_U6M,
    m.MEDICO_DIAS_MODIFICADOS_SUM_ISAPRE_U12M,
    m.MEDICO_DIAS_MODIFICADOS_SUM_ISAPRE_U24M,
    m.MEDICO_DIAS_MODIFICADOS_SUM_ISAPRE_U36M,
    m.MEDICO_DIAS_MODIFICADOS_PCT_ISAPRE_U1M,
    m.MEDICO_DIAS_MODIFICADOS_PCT_ISAPRE_U6M,
    m.MEDICO_DIAS_MODIFICADOS_PCT_ISAPRE_U12M,
    m.MEDICO_DIAS_MODIFICADOS_PCT_ISAPRE_U24M,
    m.MEDICO_DIAS_MODIFICADOS_PCT_ISAPRE_U36M,
    m.MEDICO_TASA_RATIFICACION_COMPIN_U6M,
    m.MEDICO_TASA_RATIFICACION_COMPIN_U12M,
    m.MEDICO_TASA_RATIFICACION_COMPIN_U24M,
    m.MEDICO_TASA_RATIFICACION_COMPIN_U36M,
    -- Nombres corregidos de PRESTADOR_LOCAL (no PL)
    m.PRESTADOR_LOCAL_LM_RECHAZADAS_ISAPRE_U1M AS PL_LM_RECHAZADAS_ISAPRE_U1M,
    m.PRESTADOR_LOCAL_LM_RECHAZADAS_ISAPRE_U6M AS PL_LM_RECHAZADAS_ISAPRE_U6M,
    m.PRESTADOR_LOCAL_LM_RECHAZADAS_ISAPRE_U12M AS PL_LM_RECHAZADAS_ISAPRE_U12M,
    m.PRESTADOR_LOCAL_LM_RECHAZADAS_ISAPRE_U24M AS PL_LM_RECHAZADAS_ISAPRE_U24M,
    m.PRESTADOR_LOCAL_LM_RECHAZADAS_ISAPRE_U36M AS PL_LM_RECHAZADAS_ISAPRE_U36M,
    m.PRESTADOR_LOCAL_LM_RECIBIDAS_TOTAL_U1M AS PL_LM_RECIBIDAS_TOTAL_U1M,
    m.PRESTADOR_LOCAL_LM_RECIBIDAS_TOTAL_U6M AS PL_LM_RECIBIDAS_TOTAL_U6M,
    m.PRESTADOR_LOCAL_LM_RECIBIDAS_TOTAL_U12M AS PL_LM_RECIBIDAS_TOTAL_U12M,
    m.PRESTADOR_LOCAL_LM_RECIBIDAS_TOTAL_U24M AS PL_LM_RECIBIDAS_TOTAL_U24M,
    m.PRESTADOR_LOCAL_LM_RECIBIDAS_TOTAL_U36M AS PL_LM_RECIBIDAS_TOTAL_U36M,
    m.EMPLEADOR_TASA_RECHAZO_ISAPRE_U1M,
    m.EMPLEADOR_TASA_RECHAZO_ISAPRE_U6M,
    m.EMPLEADOR_TASA_RECHAZO_ISAPRE_U12M,
    m.EMPLEADOR_TASA_RECHAZO_ISAPRE_U36M,
    m.EMPLEADOR_DIAS_SOLICITADOS_LM_U1M,
    m.EMPLEADOR_DIAS_SOLICITADOS_LM_U6M,
    m.EMPLEADOR_DIAS_SOLICITADOS_LM_U12M,
    m.EMPLEADOR_DIAS_SOLICITADOS_LM_U36M,
    m.EMPLEADOR_TASA_MODIFICACION_DIAS_ISAPRE_U1M,
    m.EMPLEADOR_TASA_MODIFICACION_DIAS_ISAPRE_U6M,
    m.EMPLEADOR_TASA_MODIFICACION_DIAS_ISAPRE_U12M,
    m.EMPLEADOR_TASA_MODIFICACION_DIAS_ISAPRE_U36M,
    m.HIST_HV_N_PRESTACIONES_U6M,
    m.HIST_HV_N_MEDICOS_U6M,
    m.HIST_HV_SUM_CANTIDAD_PREST_U6M,
    m.HIST_HV_N_HOSP_U6M,
    m.HIST_HV_N_CONSULTAS_AMB_U6M,
    m.HIST_HV_DIAS_CAMA_U6M,
    m.HIST_HV_FLAG_GES_U6M,
    m.HIST_HV_FLAG_CAEC_U6M,
    m.HIST_HV_BONIFICADO_U6M,
    m.HIST_HV_N_PRESTACIONES_U12M,
    m.HIST_HV_DIAS_CAMA_U12M,
    m.HIST_HV_FLAG_GES_U12M,
    m.HIST_HV_CONSULTAS_MISMO_MEDICO_U1M,
    m.HIST_HV_CONSULTAS_MISMO_MEDICO_U3M,
    m.HIST_HV_CONSULTAS_MISMO_MEDICO_U6M,
    m.HIST_HV_TUVO_CONSULTA_MISMO_MEDICO_U12M,
    m.HIST_HV_EXAMENES_LAB_MISMO_MEDICO_U7D,
    m.HIST_HV_EXAMENES_LAB_MISMO_MEDICO_U14D,
    m.HIST_HV_EXAMENES_LAB_MISMO_MEDICO_U30D,
    m.HIST_HV_TUVO_EXAMENES_LAB_MISMO_MEDICO,
    m.HIST_PERITAJES_NO_ASISTE_U6M,
    m.HIST_PERITAJES_DESACUERDO_ISAPRE_U12M,
    m.HIST_TOTAL_PERITAJES_U12M,
    m.HIST_PERITAJES_ISAPRE_GANO_U6M,
    m.HIST_DIAS_DESDE_ULTIMO_PERITAJE,
    m.HIST_PERITAJES_DESACUERDO_ISAPRE_MEDICO_U12M,
    m.HIST_PERITAJE_FAVORABLE_ISAPRE_MISMO_CIE_U3M,
    
    /* ===== FEATURES CTD DESDE BOLETINES_ACCIONES (EN OPTIMIZADO) ===== */
    -- Solicitudes de información
    COALESCE(m.CTD_SOLICITUDES_INFO_U30D, 0) AS CTD_SOLICITUDES_INFO_U30D,
    COALESCE(m.CTD_SOLICITUDES_INFO_MEDICA_U30D, 0) AS CTD_SOLICITUDES_INFO_MEDICA_U30D,
    COALESCE(m.CTD_SOLICITUDES_INFO_U90D, 0) AS CTD_SOLICITUDES_INFO_U90D,
    COALESCE(m.CTD_SOLICITUDES_INFO_U365D, 0) AS CTD_SOLICITUDES_INFO_U365D,
    
    -- Peritajes
    COALESCE(m.CTD_PERITAJES_TOTAL_U30D, 0) AS CTD_PERITAJES_TOTAL_U30D,
    COALESCE(m.CTD_PERITAJES_PSIQ_U30D, 0) AS CTD_PERITAJES_PSIQ_U30D,
    COALESCE(m.FLAG_PERITAJE_PSIQ_U30D, 0) AS FLAG_PERITAJE_PSIQ_U30D,
    COALESCE(m.CTD_PERITAJES_TOTAL_U90D, 0) AS CTD_PERITAJES_TOTAL_U90D,
    m.DIAS_DESDE_ULTIMO_PERITAJE AS DIAS_DESDE_ULTIMO_PERITAJE,
    
    -- Recursos
    COALESCE(m.CTD_RECURSOS_TOTAL_U90D, 0) AS CTD_RECURSOS_TOTAL_U90D,
    m.TASA_EXITO_RECURSOS_U90D AS TASA_EXITO_RECURSOS_U90D,
    
    -- FADE CTD
    COALESCE(m.CTD_FADE_TOTAL_U30D, 0) AS CTD_FADE_TOTAL_U30D,
    COALESCE(m.FLAG_TIENE_FADE_U30D, 0) AS FLAG_TIENE_FADE_U30D,
    
    -- Indicadores adicionales
    COALESCE(m.FLAG_SOSPECHA_FRAUDE_U90D, 0) AS FLAG_SOSPECHA_FRAUDE_U90D,
    COALESCE(m.FLAG_INFORME_MEDICO_RECEP_U30D, 0) AS FLAG_INFORME_MEDICO_RECEP_U30D,
    
    -- Actividad general
    COALESCE(m.CTD_ACCIONES_TOTAL_U30D, 0) AS CTD_ACCIONES_TOTAL_U30D,
    COALESCE(m.CTD_ACCIONES_TOTAL_U90D, 0) AS CTD_ACCIONES_TOTAL_U90D,
    COALESCE(m.CTD_ACCIONES_TOTAL_U365D, 0) AS CTD_ACCIONES_TOTAL_U365D,
    COALESCE(m.VELOCIDAD_ACCIONES_U30D, 0) AS VELOCIDAD_ACCIONES_U30D,

        /* ===== MÉTRICAS DE 15 DÍAS (desde OPTIMIZADO) ===== */
    COALESCE(m.CANT_LIC_U15D, 0) AS CANT_LIC_U15D,
    COALESCE(m.CANT_LIC_CON_RESOLUCION_U15D, 0) AS CANT_LIC_CON_RESOLUCION_U15D,
    COALESCE(m.COMPIN_RATIFICA_U15D, 0) AS COMPIN_RATIFICA_U15D,
    COALESCE(m.COMPIN_DENIEGA_U15D, 0) AS COMPIN_DENIEGA_U15D,
    COALESCE(m.F_DIAS_PROMEDIO_U15D, 0) AS F_DIAS_PROMEDIO_U15D,
    COALESCE(m.TOTAL_DIAS_SOLICITADOS_U15D, 0) AS TOTAL_DIAS_SOLICITADOS_U15D,
    COALESCE(m.MAX_DIAS_SOLICITADOS_U15D, 0) AS MAX_DIAS_SOLICITADOS_U15D,
    COALESCE(m.FLAG_MULTIPLES_LIC_U15D, 0) AS FLAG_MULTIPLES_LIC_U15D,
    m.RATIO_APROBACION_U15D,
    
    /* Métricas de prestaciones */
    COALESCE(m.HV_N_PRESTACIONES_U15D, 0) AS HV_N_PRESTACIONES_U15D,
    COALESCE(m.HV_SUM_CANTIDAD_PREST_U15D, 0) AS HV_SUM_CANTIDAD_PREST_U15D,
    COALESCE(m.HV_N_MEDICOS_U15D, 0) AS HV_N_MEDICOS_U15D,
    COALESCE(m.HV_FLAG_HOSPITALARIO_U15D, 0) AS HV_FLAG_HOSPITALARIO_U15D,
    COALESCE(m.HV_FLAG_BONO_U15D, 0) AS HV_FLAG_BONO_U15D,
    COALESCE(m.HV_FLAG_REEMBOLSO_U15D, 0) AS HV_FLAG_REEMBOLSO_U15D,
    COALESCE(m.HV_FLAG_GES_U15D, 0) AS HV_FLAG_GES_U15D,
    COALESCE(m.HV_FLAG_CAEC_U15D, 0) AS HV_FLAG_CAEC_U15D,
    
    /* Métricas de peritajes */
    COALESCE(m.PERITAJES_TOTAL_U15D, 0) AS PERITAJES_TOTAL_U15D,
    COALESCE(m.PERITAJES_NO_ASISTE_U15D, 0) AS PERITAJES_NO_ASISTE_U15D,
    COALESCE(m.PERITAJES_DESACUERDO_U15D, 0) AS PERITAJES_DESACUERDO_U15D,
    COALESCE(m.PERITAJES_ACUERDO_U15D, 0) AS PERITAJES_ACUERDO_U15D,
    COALESCE(m.DIAS_DESDE_ULTIMO_PERITAJE_U15D, 9999) AS DIAS_DESDE_ULTIMO_PERITAJE_U15D,
    COALESCE(m.FLAG_PERITAJE_RECIENTE_U15D, 0) AS FLAG_PERITAJE_RECIENTE_U15D,
    
    /* ===== LEAK (DATA LEAKAGE TESTING) ===== */
    m.REC_GLS_CAUMOD AS LEAK_CAUSALES,
    --m.FUERA_PLAZO AS LEAK_FUERA_DE_PLAZO,
    m.REC_LCC_VISJUS AS LEAK_GLOSAS,
    CASE 
        WHEN UPPER(m.ESTADO_LM) = 'EN VISACION' THEN NULL
        ELSE m.I_DIASAUTORIZADOS
    END AS LEAK_DIASAUTORIZADOS,
    m.ESTADO_LM AS LEAK_ESTADOLM,
    m.PERITAJE_FALLO_1 AS LEAK_FALLO_PE,
    m.PASO_FASTTRACK AS LEAK_FT,
    m.FECHA_RESOLUCION_COMPIN AS LEAK_FECHA_COMPIN,
    m.RESOLUCION_COMPIN AS LEAK_RESOLUCION_COMPIN,
    
    /* ===== TARGETS ===== */
    CASE 
        WHEN UPPER(m.ESTADO_LM) = 'EN VISACION' THEN NULL
        WHEN m.PERITAJE_LM_PERITADA = 1 THEN 1
        ELSE 0
    END AS TARGET_PERITAJE,
    CASE 
        WHEN UPPER(m.ESTADO_LM) = 'EN VISACION' THEN NULL
        WHEN m.CTD_ENVIA_PERITAJE > 0 THEN 1
        WHEN m.CTD_ENVIA_INFORME_MEDICO > 0 THEN 1
        ELSE 0
    END AS TARGET_PERITAJE2,
    CASE 
        WHEN m.ESTADO_LM = 'EN VISACION' THEN NULL
        WHEN m.I_DIASAUTORIZADOS = 0 THEN 1
        ELSE 0
    END AS TARGET_RECHAZA,
    CASE 
        WHEN m.ESTADO_LM = 'EN VISACION' THEN NULL
        WHEN m.I_DIASAUTORIZADOS < m.DIASSOLICITADO AND m.DIASSOLICITADO > 0 THEN 1
        ELSE 0
    END AS TARGET_MODIFICA,
    CASE 
        WHEN m.ESTADO_LM = 'EN VISACION' THEN NULL
        WHEN m.I_DIASAUTORIZADOS = m.DIASSOLICITADO AND m.I_DIASAUTORIZADOS > 0 THEN 1
        WHEN m.I_DIASAUTORIZADOS < m.DIASSOLICITADO THEN 0
        ELSE null
    END AS TARGET_APRUEBA,
    CASE 
        WHEN UPPER(m.RESOLUCION_COMPIN) = 'RATIFICA' THEN 1
        WHEN UPPER(m.RESOLUCION_COMPIN) = 'DENIEGA' THEN 0
        ELSE NULL
    END AS TARGET_RATIFICA,
    CASE WHEN m.FECHA_EMISION_DT IS NOT NULL THEN 1 ELSE 0 END AS TARGET_REQUIERE_REVISION,
    
    /* ===== TARGET REFINADO PARA FAST TRACK 2.0 ===== */
  CASE
      -- Si no hay dictamen o es postnatal, NULL (excluir del modelo)
      WHEN UPPER(m.ESTADO_LM) = 'EN VISACION' THEN NULL
      WHEN m.I_DIASAUTORIZADOS IS NULL THEN NULL
      WHEN m.CIE_GRUPO IN ('PARTO', 'PUERPERIO') THEN NULL

      -- Casos aprobables (TARGET_FT2 = 1)
      WHEN m.REC_GLS_CAUMOD = 'SIN OBSERVACIONES' AND m.PERITAJE_FALLO_1 IS NULL THEN 1
      WHEN m.I_DIASAUTORIZADOS = m.DIASSOLICITADO
           AND m.I_DIASAUTORIZADOS > 0
      THEN 1  -- Aprobable

      -- Cualquier otro caso requiere revisión
      ELSE 0  -- No aprobable (requiere revisión)
  END AS TARGET_FT2,

    CASE
      -- Si no hay dictamen o es postnatal, NULL (excluir del modelo)
      WHEN UPPER(m.ESTADO_LM) = 'EN VISACION' THEN NULL
      WHEN m.PASO_FASTTRACK = 1 THEN NULL
      WHEN m.CIE_GRUPO IN ('PARTO', 'PUERPERIO') THEN NULL

      -- Casos aprobables (TARGET_FT3 = 1)
      WHEN m.REC_GLS_CAUMOD = 'SIN OBSERVACIONES' THEN 1
      WHEN m.I_DIASAUTORIZADOS = m.DIASSOLICITADO
           AND m.I_DIASAUTORIZADOS > 0
      THEN 1  -- Aprobable

      -- Cualquier otro caso requiere revisión
      ELSE 0  -- No aprobable (requiere revisión)
  END AS TARGET_FT3
    
FROM 
    OPX.P_DDV_OPX_MDPREDICTIVO.MODELO_LM_202507_OPTIMIZADO AS m
WHERE 
    m.FECHA_EMISION_DT < current_date();
